# Generated by Django 4.2.4 on 2023-08-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0002_alter_ticket_assigned_to_assignedticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_tickets_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to='ticketsystem.user'),
        ),
    ]
